filebeat.prospectors:
    - 
      input_type: log
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: false
      multiline.match: after
      fields:
        log_topics: new-shushang-matrix-admin-catalina-logs
      paths:
        - /data/tomcat/logs/catalina.*
tags: ["matrix-admin-leader","new-shushang"]
tail_files: true
close_older: 1h
force_close_file: true

output.kafka:
  enabled: true
  partition.round_robin:
    reachable_only: false
  hosts: ["10.20.135.163:9092","10.20.125.29:9092","10.20.125.30:9092"]
  topic: '%{[fields][log_topics]}'
